# 这些是支持这个项目的方式

github: ConcaXu
patreon: # 用你的Patreon用户名替换
open_collective: # 用你的Open Collective用户名替换
ko_fi: # 用你的Ko-fi用户名替换
tidelift: # 用你的Tidelift平台名称替换
community_bridge: # 用你的Community Bridge项目名称替换
liberapay: # 用你的Liberapay用户名替换
issuehunt: # 用你的IssueHunt用户名替换
otechie: # 用你的Otechie用户名替换
lfx_crowdfunding: # 用你的LFX Crowdfunding项目名称替换
custom: ['https://www.buymeacoffee.com/concaxu'] # 用你的自定义URL替换